name: Build & Release

on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  build-linux:
    name: Build Linux (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: go.mod
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: frontend/package.json
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Linux dependencies
        run: task build:deps
      - name: Build & Archive Linux binaries
        run: |
          task build:prod ARCH=${{ matrix.arch }}
          tar -czvf Zen_linux_${{ matrix.arch }}.tar.gz -C build/bin Zen
          task build:prod-noupdate ARCH=${{ matrix.arch }}
          tar -czvf Zen_linux_${{ matrix.arch }}_noselfupdate.tar.gz -C build/bin Zen
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: linux-${{ matrix.arch }}
          path: |
            Zen_linux_${{ matrix.arch }}.tar.gz
            Zen_linux_${{ matrix.arch }}_noselfupdate.tar.gz

  build-macos:
    name: Build macOS (${{ matrix.arch }})
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: go.mod
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: frontend/package.json
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install macOS dependencies
        run: task build:deps
      - name: Set up keychain profile
        env:
          CI_KEYCHAIN_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}
          CERTIFICATE: ${{ secrets.PROD_MACOS_CERTIFICATE }}
          CERTIFICATE_PWD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
        run: |
          CI_KEYCHAIN_PWD=$CI_KEYCHAIN_PWD \
          CERTIFICATE=$CERTIFICATE \
          CERTIFICATE_PWD=$CERTIFICATE_PWD \
          task build:setup-keychain
      - name: Build & archive macOS artifacts
        env:
          CERTIFICATE_NAME: ${{ secrets.PROD_MACOS_CERTIFICATE_NAME }}
          NOTARIZATION_APPLE_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
          NOTARIZATION_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
          NOTARIZATION_PWD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
        run: |
          CERTIFICATE_NAME=$CERTIFICATE_NAME \
          NOTARIZATION_APPLE_ID=$NOTARIZATION_APPLE_ID \
          NOTARIZATION_TEAM_ID=$NOTARIZATION_TEAM_ID \
          NOTARIZATION_PWD=$NOTARIZATION_PWD \
          task build:prod ARCH=${{ matrix.arch }}
          tar -czvf Zen_darwin_${{ matrix.arch }}.tar.gz -C build/bin Zen.app
          mv build/bin/Zen.dmg build/bin/Zen-${{ matrix.arch }}.dmg

          CERTIFICATE_NAME=$CERTIFICATE_NAME \
          NOTARIZATION_APPLE_ID=$NOTARIZATION_APPLE_ID \
          NOTARIZATION_TEAM_ID=$NOTARIZATION_TEAM_ID \
          NOTARIZATION_PWD=$NOTARIZATION_PWD \
          task build:prod-noupdate ARCH=${{ matrix.arch }}
          tar -czvf Zen_darwin_${{ matrix.arch }}_noselfupdate.tar.gz -C build/bin Zen.app
      - name: Upload macOS artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: macos-${{ matrix.arch }}
          path: |
            Zen_darwin_${{ matrix.arch }}.tar.gz
            build/bin/Zen-${{ matrix.arch }}.dmg
            Zen_darwin_${{ matrix.arch }}_noselfupdate.tar.gz

  build-windows:
    name: Build Windows (${{ matrix.arch }})
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: go.mod
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: frontend/package.json
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Archive Windows binaries
        run: |
          task build:prod ARCH=${{ matrix.arch }}
          Compress-Archive -Path .\build\bin\Zen.exe -DestinationPath Zen_windows_${{ matrix.arch }}.zip
          task build:prod-noupdate ARCH=${{ matrix.arch }}
          Compress-Archive -Path .\build\bin\Zen.exe -DestinationPath Zen_windows_${{ matrix.arch }}_noselfupdate.zip
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: windows-${{ matrix.arch }}
          path: |
            Zen_windows_${{ matrix.arch }}.zip
            Zen_windows_${{ matrix.arch }}_noselfupdate.zip
            build/bin/Zen-${{ matrix.arch }}-installer.exe

  release:
    permissions:
      # https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds#generating-build-provenance-for-binaries
      id-token: write
      attestations: write
      # https://github.com/softprops/action-gh-release/issues/236
      contents: write
    name: Attest & Release
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: artifacts
      - name: Generate artifact attestations
        uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2.3.0
        with:
          subject-path: artifacts/**
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          files: artifacts/**
          tag_name: ${{ github.ref }}
          draft: true
